defaultPortal: Geeth-Engaging
portals:
  - name: Geeth-Engaging
    portalId: 43811880
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPXxysioMRIOAAUAQAAAAGwAQAJYAgEYqIjyFCDh2OUcKO7pDDIUDsTKm85W-dqv8S43t93QPdoyDuA6MAAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgA0IUDjrzlCB3hRXtfnxn6O2xj5_78IVKA25hMVIAWgA
        expiresAt: '2023-09-12T11:07:00.237Z'
    personalAccessKey: >-
      CiRjZDc2Zjk5My0yNzczLTQxOGQtODVhOC05OTVkMjhmNTZiOTAQqIjyFBjh2OUcKhkABeaRgmKRRvp4N7DceVVM1o9IBLvpIqMJSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
