defaultPortal: Geeth-Engaging
portals:
  - name: Geeth-Engaging
    portalId: 43811880
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CI_t4o-rMRIOAAUAQAAAAGwAQAJYAgEYqIjyFCDh2OUcKO7pDDIUb2Kq_7wJKwQpY9KVY1lp1-GqpAw6MAAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgA0IU19pAzbGO--levI0sZP9QcoNIWsdKA25hMVIAWgA
        expiresAt: '2023-09-20T09:43:01.546Z'
    personalAccessKey: >-
      CiRjZDc2Zjk5My0yNzczLTQxOGQtODVhOC05OTVkMjhmNTZiOTAQqIjyFBjh2OUcKhkABeaRgmKRRvp4N7DceVVM1o9IBLvpIqMJSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
